### PR TITLE
Rename repo to UniViz. Also update the package and readme files

### PR DESCRIPTION
**Pull request by kaveh096**

### CODE REVIEW

**Comment by ccondit** [comment]
https://github.com/googleinterns/univiz/pull/15 should have resolved the MD issue. Sync to the latest from the main branch.

**Comment by kaveh096** [comment]
> #15 should have resolved the MD issue. Sync to the latest from the main branch.

done

**Comment by kaveh096** [comment]
> Do the diffs from the main branch always show up in the PR tool?

i actually had the same question. is there anything i can do to hide the changes i pulled from master?

**Comment by ccondit** [comment]
> > Do the diffs from the main branch always show up in the PR tool?
> 
> i actually had the same question. is there anything i can do to hide the changes i pulled from master?

¯\_(ツ)_/¯

**Pull request merged**
