### PR TITLE
Adds APIKey file to .gitignore

### PR DESCRIPTION
**Pull request by mmurray22**
As the title states, this PR adds APIKey file to the .gitignore

### CODE REVIEW

**Comment by biancamacias** [comment]
> LGTM, though maybe it shouldn't specifically be for the CollegeScoreCard API key, since we'll probably have other API keys to use within the package.

you mean instead of adding each file that contains an API key?

**Comment by mmurray22** [comment]
Yep, I can change the name of the java file to make it more generic! Thanks for the comment!

**Comment by mmurray22** [comment]
@ccondit you can either take over this PR or start a new one!

**Comment by ccondit** [comment]
> @ccondit you can either take over this PR or start a new one!

I'm following up in https://github.com/googleinterns/univiz/pull/33. You can go ahead and delete this branch / PR.

**Pull request closed without merging**
